"""Add table stuff

Revision ID: 53d8ed6eb549
Revises: 8fe008da8f55
Create Date: 2023-03-21 14:39:25.782932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d8ed6eb549'
down_revision = '8fe008da8f55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
